image: Visual Studio 2013
clone_folder: "c:\\stack"
environment:
  global:
    WIXBIN: "c:\\Program Files (x86)\\WiX Toolset v3.11\\bin"
    CABAL_STORE: "C:\\cs"
    CABAL_PACKAGE_DB: "%CABAL_STORE%\\ghc-%GHC_MINOR_VERSION%\\package.db"
    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"
    # see #4201, https://github.com/haskell-tools/haskell-tools/issues/277
  matrix:
  - OSARCH: "windows-x86_64"
    GHC_VERSION: "8.6.1.1"
    GHC_MINOR_VERSION: "8.6.1"
    GHC: "C:\\ProgramData\\chocolatey\\lib\\ghc\\tools\\ghc-%GHC_MINOR_VERSION%\\bin\\ghc.exe"
    CABAL_VERSION: "2.4.0.0"
    CABAL_OPTS: "-fhighlighting --disable-optimization"
    GHC_OPTS: "-fhide-source-paths"
    ARCH: "x64"
    CHOCO_OPTS: ""

cache:
  - '%CABAL_STORE%'

# We don't do a normal C build, but build in test_script via stack
build: off

install:
  - choco install wixtoolset --version 3.11.1 %CHOCO_OPTS%
  - choco install ghc --version %GHC_VERSION% --ignore-dependencies %CHOCO_OPTS%
  - choco install cabal --version %CABAL_VERSION% --ignore-dependencies %CHOCO_OPTS%

test_script:
  # Note: this forces creation of cabal store, because of a cabal bug:
  # see https://github.com/haskell/cabal/issues/5516
  - cabal --store-dir="%CABAL_STORE%" --version
  - cabal --store-dir="%CABAL_STORE%" new-update
  - mkdir "tmp" && cd "tmp" && echo "" | cabal new-repl -w %GHC% && cd ".."
  - cabal --store-dir="%CABAL_STORE%" new-configure -w %GHC% --enable-tests %CABAL_OPTS% --ghc-options="%GHC_OPTS%"
  - cabal --store-dir="%CABAL_STORE%" new-build
  - cabal --store-dir="%CABAL_STORE%" new-test
