clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    STACK_YAML: "c:\\stack\\stack.yaml"
    WIXBIN: "c:\\Program Files (x86)\\WiX Toolset v3.10\\bin"

cache:
  - "c:\\sr" # stack root, short paths == fewer problems
  - "c:\\stack\\stack.exe"

# We don't do a normal C build, but build in test_script via stack
build: off

install:
  - |
      stack --version || curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386 && 7z x stack.zip stack.exe
  - stack setup > nul

test_script:
  # The ugly echo "" hack is to avoid complaints about 0 being an invalid file
  # descriptor
  - echo "" | stack clean
  - echo "" | stack --no-terminal test

